package cz.stu.gfx;

public enum Sprite {
    BRICK, STEEL,
    UNDAMAGED_EAGLE, DESTOYED_EAGLE,
    EXPLOSION_1, EXPLOSION_2, EXPLOSION_3,
    PLAYER_UP, PLAYER_DOWN, PLAYER_LEFT, PLAYER_RIGHT,
    ENEMY_UP, ENEMY_DOWN, ENEMY_LEFT, ENEMY_RIGHT
}
